services:
  self_bot:
    container_name: tumblr-bridge-self

    image: "ghcr.io/sillygir1/tumblr-tg-bridge:main"
    restart: unless-stopped

    env_file: "tumblr_bridge.env"
    environment:
      # Output to docker logs:
      DEBUG: "True"
      # You can remove one of the modes if that's what you want
      # MODE: "bridge"
      MODE: "bridge, inline"
      BLOG_NAME: "BLOG_NAME" # REPLACE THIS
      TELEGRAM_CHAT_ID: "YOUR_CHAT_ID" # REPLACE THIS
      # Update interval (in seconds) for the bridge mode:
      UPDATE_TIME: "30"
      # List of users who are allowed to use inline mode:
      ALLOWED_USERS: "USER_ID_1, USER_ID_2, ..., USER_ID_9000" # REPLACE THIS
